### ISSUE TITLE
Dropbear session in SLURM job does not inherit $SLURM_JOB_ID and other SLURM environment variables

### ISSUE THREAD

**Issue by LazDaria** [e-dorigatti/e-dorigatti.github.io#17]
First, thank you for providing this elegant solution to tie a Visual Studio Code session to a SLURM job using Dropbear. The setup works in terms of job association, as canceling the SLURM job correctly terminates the VSCode session.

However, I’ve noticed that key SLURM environment variables, such as $SLURM_JOB_ID, $SLURM_CPUS_PER_TASK, and $CUDA_VISIBLE_DEVICES, are not passed into the VSCode session leading to processes accessing all GPUs on the node, rather than being restricted to the allocated GPUs.

Can you confirm if this behavior is reproducible on your end or if it could be due to a configuration issue on my side?

Thanks.

**Comment by e-dorigatti** [comment]
Hi @LazDaria, thanks for pointing this out. I also do not see those environment variables, however both `nvidia-smi` and `torch.cuda.device_count()` work as expected for me, reporting only one of the four GPUs on the node when I run these commands within VSCode or directly connecting to dropbear. I am not sure what our infrastructure team is doing to make this work.

As a workaround, you could save the environment in a file before starting dropbear:

```
> cat run-vscode-server-gpu.sh

env | grep 'SLURM\|CUDA\|NVIDIA' > ~/vscode-gpu-env.txt

# start dropbear
```

Now you can use that as an env file in VSCode, e.g. via the `python.envFile` [setting](https://code.visualstudio.com/docs/python/environments#_environment-variable-definitions-file), or in the terminal:

```
> source ~/vscode-gpu-env.txt && python program.py ...   # available only for this command
> export $(cat ~/vscode-gpu-env.txt)  # available globally this shell
```

**Comment by LazDaria** [comment]
Thank you for your prompt answer.  It seems that in my case, SLURM is not enforcing any resource restrictions. `nvidia-smi` and `torch.cuda.device_count()` list all GPUs on the node (not limited to the allocated ones), also SLURM does not seem to enforce restrictions for other resources, such as memory and CPUs.

Maybe Dropbear explicitly requires additional configuration to respect SLURM limits..
Thank you for your help. I'd appreciate any further hints.

**Comment by e-dorigatti** [comment]
I'm sorry that this is not working for you @LazDaria. Another thing that you could try is to directly [launch the VSCode server](https://code.visualstudio.com/blogs/2022/12/07/remote-even-better) in the SLURM job, rather than dropbear.

**Comment by LazDaria** [comment]
The approach you suggested works. I just added the lines below to my job script to make sure that the env variables are cleaned up on job termination. 

```
### Save SLURM variables according to https://github.com/microsoft/vscode-remote-release/issues/1722
cleanup() {
    echo "Caught signal - removing SLURM env file"
    rm -f ~/.slurm-envvar.bash
}

# Trap the timeout signal (SIGTERM) and call the cleanup function
trap 'cleanup' SIGTERM

# store SLURM variables to file
env | awk -F= '$1~/^(SLURM|CUDA|NVIDIA_)/{print "export "$0}' > ~/.slurm-envvar.bash
```

And added these lines to my .bashrc:

```
# Source SLURM environment if connecting through code-tunnel
[ -f ~/.slurm-envvar.bash ] && source ~/.slurm-envvar.bash
```

Thank you again for your blog. It really makes my life a lot easier.

**Comment by e-dorigatti** [comment]
Glad to hear that you managed to make it work, @LazDaria, and I'm very happy you found my blog useful! If you do not mind, I will add this solution to the main post to help others who may have the same problem.

**Comment by LazDaria** [comment]
Of course, please do so!
